### ISSUE TITLE
Review dependencyof 'numpngw>=0.0.8' in setup.py

### ISSUE THREAD

**Issue by gqueiroz** [brazil-data-cube/bdc-collection-builder#135]

**Comment by raphaelrpl** [comment]
This dependency is related with quicklook generation as following [`bdc_collection_builder.celery.publish` L68](https://github.com/brazil-data-cube/bdc-collection-builder/blob/31f5aa13553cc2dda7b5daecd967ef694627fa20/bdc_collection_builder/celery/publish.py#L68).
